---
- name: Create directories if non-existent
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - ~/.config/htop
    - ~/.config/alacritty
    - ~/.config/nvim
    - ~/.ssh

- name: Create configurations
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/dots/{{ item.src }}"
    dest: "{{ item.dest }}"
    force: no
  loop:
    - { src: "shell/.gitconfig", dest: ~/.gitconfig }
    - { src: "shell/tmux.conf", dest: ~/.tmux.conf }
    - { src: "shell/htoprc", dest: ~/.config/htop/htoprc }
    - { src: "shell/starship.toml", dest: ~/.config/starship.toml }

- name: Create desktop configurations
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/dots/{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: true
  loop:
    - { src: "{{ playbook_dir }}/desktop/alacritty.yml", dest: ~/.config/alacritty/alacritty.yml}
  tags: [ 'never', 'desktop' ]

- name: Copy .gitconfig template
  copy:
    src: "{{ playbook_dir }}/dots/shell/.gitconfig"
    dest: "~/.gitconfig"
    force: no
