---
- name: Install basic shell/cli packages
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - htop
    - curl
    - wget
    - jq
    - "{{ 'fzf' if ansible_distribution not in ['CentOS', 'RedHat', 'OracleLinux'] else '' }}"

- name: Install fzf (EL)
  block:
    - name: Git checkout
      ansible.builtin.git:
        repo: https://github.com/junegunn/fzf.git
        dest: /tmp/fzf
    - name: Get fzf binary
      become: yes
      shell: cd /tmp/fzf && ./install --all
    - name: Install fzf binary
      become: yes
      shell: cp /tmp/fzf/bin/* /usr/local/bin
  when: ansible_distribution in ['CentOS', 'RedHat', 'OracleLinux']


- include_tasks: nvim.yml
  ignore_errors: yes
- include_tasks: configs.yml

- include_tasks: install-others.yml
