---
# vars file
#

base_packages:
  - bash-completion
  - unzip

graphical_packages:
  - "@firefox"
  - chromium-browser  
  - alacritty
  - zram
  - libappindicator

codecs_packages:
  - compat-ffmpeg28
  - compat-ffmpeg28-devel
  - egl-utils
  - egl-wayland
  - flac
  - ffmpeg
  - ffmpeg-libs
  - gstreamer1-libav
  - gstreamer1-plugins-bad-free
  - gstreamer1-plugins-bad-freeworld
  - gstreamer1-plugins-base
  - gstreamer1-plugins-base-tools
  - gstreamer1-plugins-good
  - gstreamer1-plugins-good-extras
  - gstreamer1-plugins-ugly
  - gstreamer1-plugins-ugly-free
  - gstreamer1-svt-av1
  - gstreamer1-svt-vp9
  - gstreamer1-vaapi
  - intel-media-driver
  - libva-devel
  - libva-intel-driver
  - libva-intel-hybrid-driver
  - libva-utils
  - libva-vdpau-driver
  - libvdpau-va-gl
  - vlc
