---
- name: Ensure snap is installed
  package:
    state: present
    name: snapd
  become: yes

- name: Make a symlink for classic snaps
  ansible.builtin.file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
  become: yes
  when: ansible_os_family == "RedHat"

- name: Install desktop snaps
  include: desktop.yml
  tags: [ 'never', 'desktop' ]
