apiVersion: v1
kind: Namespace
metadata:
  name: sandbox
  labels:
    cert-manager-tls: sandbox # Define namespace label for kubed
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-example-org-cert
  namespace: cert-manager
spec:
  commonName: '*.k8s.example.org'
  secretName: k8s-example-org-cert
  dnsNames:
    - 'k8s.example.org'
    - '*.k8s.example.org'
  issuerRef:
    name: example-issuer
    kind: ClusterIssuer
  secretTemplate:
    annotations:
      kubed.appscode.com/sync: ""
