apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-token: your-token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: example-issuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: internal@gmail.com
    privateKeySecretRef:
      name: example-issuer
    solvers:
    - dns01:
        cloudflare:
          email: internal@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
